name: Build
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: mozilla-mobile/firefox-android
      - name: Build
        run: |
          export ANDROID_HOME=/woodpecker/android-sdk
          apt update
          apt -y install --no-install-recommends unzip bzip2 git
          wget -q -O commandlinetools-linux.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux.zip -d "$ANDROID_HOME"
          mkdir "$ANDROID_HOME/licenses"
          echo 24333f8a63b6825ea9c5514f83c2829b004d1fee | tee "$ANDROID_HOME/licenses/android-sdk-license"
          mkdir -p "$HOME/.android"
          echo "${{ secrets.SIGN_STORE_DATA }}" | base64 -d >"$HOME/.android/debug.keystore"
          cd fenix
          sed -zi 's/\.aboutConfigEnabled([^()]\+)/.aboutConfigEnabled(true)/' app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
          echo "org.gradle.daemon=false" | tee -a gradle.properties
          echo "autosignReleaseWithDebugKey" | tee -a local.properties
          ./gradlew assembleRelease
          curl -X POST -H "Authorization: Bearer ${{ secrets.DEPLOYGATE_TOKEN }}" -F file=@app/build/outputs/apk/fenix/release/app-fenix-arm64-v8a-release.apk https://deploygate.com/api/users/yogpstop/apps
          shred -u "$HOME/.android/debug.keystore"
