name: Debug
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17
    steps:
      - name: Build
        run: |
          sed -i "s:/root:$HOME:" /etc/passwd
          id
          getent passwd
          set
          ls -ld $HOME /root
          ls -lA $HOME /root
