name: Debug
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eclipse-temurin:17
    steps:
      - name: Build
        run: |
          id
          getent passwd
          set
          ls -ld ~ $HOME /root
          ls -lA /root
          mkdir -p "$HOME/.android"
          echo "${{ secrets.SIGN_STORE_DATA }}" | base64 -d >"$HOME/.android/debug.keystore"
          ls -ld "$HOME/.android/debug.keystore"
          keytool -list -v -keystore "$HOME/.android/debug.keystore" -storepass android
          mkdir -p "/root/.android"
          echo "${{ secrets.SIGN_STORE_DATA }}" | base64 -d >"/root/.android/debug.keystore"
          ls -ld "/root/.android/debug.keystore"
          keytool -list -v -keystore "/root/.android/debug.keystore" -storepass android
